apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: cmbu-app-frontend
  namespace: ${input.GIT_COMMIT_ID}-namespace
  labels:
    app: bootcamp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bootcamp
      role: web
      tier: frontend
  template:
    metadata:
      labels:
        app: bootcamp
        role: web
        tier: frontend
    spec:
      containers:
      - name: frontend
        image: ${input.baseRepo}/cmbu-app-frontend:latest
        ports:
        - containerPort: 80